Fixed TypeError: String required
Traceback (most recent call last):
  File "D:\3144\sublime_plugin.py", line 330, in on_new
    callback.on_new(v)
  File "default_syntax in Installed Packages\Default Syntax.sublime-package", line 13, in on_new
  File "D:\3144\sublime.py", line 1069, in set_syntax_file
    self.assign_syntax(syntax_file)
  File "D:\3144\sublime.py", line 1065, in assign_syntax
    sublime_api.view_assign_syntax(self.view_id, syntax_file)
TypeError: String required